name: rtd
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - westpa>=2022.03
    - scikit-learn
    - tqdm
    - sphinx-argparse
    - matplotlib
    - networkx
    - mock
    - pillow
    - sphinx
    - sphinx_rtd_theme
    - pip
    - pip:
        - pylcs
        - ray
        - timedinput
        - recommonmark
        - readthedocs-sphinx-ext

