# .readthedocs.yml

version: 2
sphinx:
  # Path to Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: miniforge3-latest

python:
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/environment-rtd.yml
